version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
    networks:
      - rmq
    volumes:
      - db:/var/lib/postgresql/data


  flower:
    build: flower
    depends_on:
      - rabbitmq
    ports:
      - 5555:5555
    networks:
      - rmq

  celery-master:
    build: celery-master
    depends_on:
      - rabbitmq
    networks:
      - rmq

  client:
    build: client
    environment:
      - FLASK_DEBUG=1
    depends_on:
      - rabbitmq
      - celery-master
    ports:
      - 5000:5000
    networks:
      - rmq
    volumes:
      - ./client:/app

networks:
  rmq:

volumes:
  rabbitmq_data:
  db:
